<script setup lang="ts">
/**
 * Run detail page (`/runs/:id`, generated by unplugin-vue-router from this
 * folder). Owns the single-run query + live polling (`useRunDetail`) and the
 * status-gated action buttons: Resume/Skip (`blocked`), Merge/Wait
 * (`awaiting_confirmation`, via `confirmRoutine`), Cancel (any non-terminal
 * status, behind a `ConfirmDialog` matching `RunsListSection`'s Cancel flow).
 * The list lives in `./index.vue` (the former flat `runs.vue`).
 */
import { computed, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { Alert, Badge, Button, ConfirmDialog, Icon, Skeleton, Text } from '@shared/ui/design-system'
import {
  RunStatusChip,
  StepStatusChip,
  flowLabel,
  formatDateTime,
  isRunCancelable,
  routineKindLabel,
  runTitle,
  stateSummaryEntries,
  useRunDetail,
} from '@modules/runs'
import type { RoutineConfirmDecision } from '@modules/runs'

const route = useRoute('/runs/[id]')
const id = computed(() => String(route.params.id))

const {
  run,
  state,
  error,
  refetch,
  isPolling,
  pausePolling,
  resumeRun,
  isResuming,
  skipRun,
  isSkipping,
  confirmRun,
  isConfirming,
  cancelRun,
  isCancelling,
} = useRunDetail(id)

// Mirrors RunsListSection's onUnmounted pause — the composable's polling
// `watch` has no idea this page navigated away.
onUnmounted(() => {
  pausePolling()
})

async function handleResume() {
  try {
    await resumeRun()
  } catch {
    // no-op — composable already toasted the error
  }
}

async function handleSkip() {
  try {
    await skipRun()
  } catch {
    // no-op — composable already toasted the error
  }
}

async function handleConfirm(decision: RoutineConfirmDecision) {
  try {
    await confirmRun(decision)
  } catch {
    // no-op — composable already toasted the error
  }
}

async function handleCancel() {
  try {
    await cancelRun()
  } catch {
    // no-op — composable already toasted the error
  }
}
</script>

<template>
  <div class="flex flex-col gap-4">
    <RouterLink
      to="/runs"
      class="inline-flex w-fit items-center gap-1.5 text-sm text-text-muted transition-colors hover:text-text focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"
    >
      <Icon name="chevron-down" size="sm" class="rotate-90" />
      Runs
    </RouterLink>

    <div v-if="state.status === 'pending'" class="flex flex-col gap-2" data-testid="run-detail-loading">
      <Skeleton class="h-6 w-64" />
      <Skeleton class="h-4 w-40" />
      <Skeleton class="h-24 w-full" />
    </div>

    <Alert v-else-if="state.status === 'error'" status="danger">
      <p>{{ error?.message ?? 'Failed to load run' }}</p>
      <Button variant="outline" size="sm" class="mt-2" @click="refetch()">Retry</Button>
    </Alert>

    <template v-else-if="run">
      <section class="flex flex-col gap-2">
        <div class="flex items-center gap-2">
          <Text muted size="sm">{{ run.repoName ?? 'Unknown repo' }}</Text>
          <span
            v-if="isPolling"
            class="flex items-center gap-1 text-xs text-text-muted"
            data-testid="run-detail-live-indicator"
          >
            <span class="size-1.5 animate-pulse rounded-full bg-success-solid motion-reduce:animate-none" />
            Live
          </span>
        </div>
        <Text as="h1" size="xl" class="font-semibold tracking-tight">{{ runTitle(run) }}</Text>
        <div class="flex flex-wrap items-center gap-2">
          <RunStatusChip :status="run.status" />
          <Badge status="neutral">{{ routineKindLabel[run.kind] }}</Badge>
          <Badge v-if="run.kind === 'release' && flowLabel(run.flow)" status="neutral">
            {{ flowLabel(run.flow) }}
            <template v-if="run.sourceBranch && run.targetBranch">
              — {{ run.sourceBranch }}→{{ run.targetBranch }}
            </template>
          </Badge>
          <Text muted size="xs">
            Created {{ formatDateTime(run.createdAt) }} · Updated {{ formatDateTime(run.updatedAt) }}
          </Text>
        </div>
      </section>

      <Alert v-if="run.lastError" status="danger" title="Last error" data-testid="run-last-error">
        {{ run.lastError }}
      </Alert>

      <section
        v-if="stateSummaryEntries(run).length > 0"
        class="flex flex-col gap-2 rounded-lg border border-line-subtle bg-bg-panel p-3"
      >
        <Text size="sm" class="font-medium">State</Text>
        <dl class="grid grid-cols-2 gap-x-4 gap-y-2 sm:grid-cols-3">
          <div v-for="entry in stateSummaryEntries(run)" :key="entry.key" class="flex flex-col">
            <dt class="text-xs text-text-muted">{{ entry.label }}</dt>
            <dd class="text-sm text-text">{{ entry.value }}</dd>
          </div>
        </dl>
      </section>

      <section class="flex flex-col gap-2">
        <Text size="sm" class="font-medium">Steps</Text>
        <ol v-if="run.steps.length > 0" class="flex flex-col gap-2" data-testid="run-step-list">
          <li
            v-for="step in run.steps"
            :key="step.name"
            class="flex items-center justify-between gap-3 rounded-lg border border-line-subtle bg-bg-panel px-3 py-2"
            data-testid="run-step-row"
          >
            <div class="flex min-w-0 flex-col gap-0.5">
              <Text class="truncate font-medium">{{ step.name }}</Text>
              <Text muted size="sm" class="truncate">{{ step.detail }}</Text>
            </div>
            <StepStatusChip :status="step.status" />
          </li>
        </ol>
        <Text v-else muted size="sm">No steps recorded yet.</Text>
      </section>

      <section
        v-if="run.status === 'blocked' || run.status === 'awaiting_confirmation' || isRunCancelable(run.status)"
        class="flex flex-wrap items-center gap-2"
      >
        <Button v-if="run.status === 'blocked'" variant="accent" size="sm" :loading="isResuming" @click="handleResume">
          Resume
        </Button>
        <Button v-if="run.status === 'blocked'" variant="outline" size="sm" :loading="isSkipping" @click="handleSkip">
          Skip
        </Button>
        <template v-if="run.status === 'awaiting_confirmation'">
          <Button variant="accent" size="sm" :loading="isConfirming" @click="handleConfirm('merge')">Merge</Button>
          <Button variant="outline" size="sm" :loading="isConfirming" @click="handleConfirm('wait')">Wait</Button>
        </template>
        <ConfirmDialog
          v-if="isRunCancelable(run.status)"
          title="Cancel this run?"
          description="Stops the routine run in progress. This cannot be undone."
          confirm-label="Cancel run"
          :pending="isCancelling"
          @confirm="handleCancel"
        >
          <template #trigger>
            <Button variant="ghost" size="sm" class="text-danger-text hover:bg-danger-bg">Cancel</Button>
          </template>
        </ConfirmDialog>
      </section>
    </template>
  </div>
</template>

<route lang="json">
{ "meta": { "title": "Run" } }
</route>
