<script setup lang="ts">
/**
 * Run detail page (`/runs/:id`, generated by unplugin-vue-router from this
 * folder). Owns the single-run query + live polling (`useRunDetail`) and the
 * status-gated action buttons: Resume/Skip (`blocked`), Merge/Wait
 * (`awaiting_confirmation`, via `confirmRoutine`) — Merge behind a danger
 * `ConfirmDialog` naming the concrete branches/tag, Wait unconfirmed — Cancel
 * (any non-terminal status, behind a `ConfirmDialog` matching
 * `RunsListSection`'s Cancel flow). The list lives in `./index.vue` (the
 * former flat `runs.vue`).
 */
import { computed, onUnmounted } from 'vue'
import { useRoute } from 'vue-router'
import { Alert, Badge, Button, ConfirmDialog, Icon, Skeleton, Text } from '@shared/ui/design-system'
import {
  RunStatusChip,
  StepTimeline,
  flowLabel,
  formatDateTime,
  isRunCancelable,
  mergeRequestUrl,
  releaseTag,
  runMergeRequestIid,
  routineKindLabel,
  runTitle,
  stateSummaryEntries,
  useRunDetail,
} from '@modules/runs'
import type { RoutineConfirmDecision } from '@modules/runs'
import { useReposStore } from '@modules/repos/store'
import { isNotFound } from '@shared/api/isNotFound'
import { resolveErrorMessage } from '@shared/api/resolveErrorMessage'

const route = useRoute('/runs/[id]')
const reposStore = useReposStore()
const id = computed(() => String(route.params.id))

const {
  run,
  state,
  error,
  refetch,
  isPolling,
  pausePolling,
  resumeRun,
  isResuming,
  skipRun,
  isSkipping,
  confirmRun,
  isConfirming,
  cancelRun,
  isCancelling,
} = useRunDetail(id)

// Mirrors RunsListSection's onUnmounted pause — the composable's polling
// `watch` has no idea this page navigated away.
onUnmounted(() => {
  pausePolling()
})

async function handleResume() {
  try {
    await resumeRun()
  } catch {
    // no-op — composable already toasted the error
  }
}

async function handleSkip() {
  try {
    await skipRun()
  } catch {
    // no-op — composable already toasted the error
  }
}

async function handleConfirm(decision: RoutineConfirmDecision) {
  try {
    await confirmRun(decision)
  } catch {
    // no-op — composable already toasted the error
  }
}

async function handleCancel() {
  try {
    await cancelRun()
  } catch {
    // no-op — composable already toasted the error
  }
}

// The merge/tag is the single most destructive action in the app — it merges
// a protected branch and pushes a tag on the real GitLab project. Name the
// concrete source/target branches and tag so the user authorizes what they
// can actually see, matching the old UI's `requestMerge` confirm (see
// packages/spa/src/modules/routines/components/RoutineRunDetail.vue), with
// generic fallbacks when a field is missing (e.g. legacy runs).
const mergeConfirmDescription = computed(() => {
  if (!run.value) return ''
  const source = run.value.sourceBranch || 'the source branch'
  const target = run.value.targetBranch || 'the target branch'
  // The tag the server will push (it appends "-dev" outside the main flow).
  const tag = releaseTag(run.value) ?? 'the next tag'
  return `This merges ${source} into ${target} on your real GitLab project and pushes tag ${tag}. This cannot be undone.`
})

// The step the run is paused on waiting for the user: the confirm gate while
// awaiting confirmation, or the step a blocked run stopped at. The timeline
// renders the decision (Merge/Wait, Resume/Skip) right under that step.
const attentionStep = computed(() => {
  const r = run.value
  if (!r) return undefined
  if (r.status === 'awaiting_confirmation') {
    return (r.steps.find((s) => s.name === 'confirm') ?? r.steps.find((s) => s.status === 'running'))?.name
  }
  if (r.status === 'blocked') {
    return (r.steps.find((s) => s.status === 'failed') ?? r.steps.find((s) => s.status === 'running'))?.name
  }
  return undefined
})

// Header links: back to the repo's Flow workspace (Actions tab, where its runs
// live) and out to the merge request on GitLab once the run has one (the main
// flow only creates it mid-run).
const repoFlowLink = computed(() => (run.value ? { path: `/flow/${run.value.repoId}`, query: { tab: 'actions' } } : null))
const mergeRequest = computed(() => {
  if (!run.value) return null
  const iid = runMergeRequestIid(run.value)
  if (iid === null) return null
  const repo = reposStore.repos.find((r) => r.id === run.value!.repoId)
  return { iid, url: repo ? mergeRequestUrl(repo.url, iid) : null }
})

const mergeSummary = computed(() => {
  if (!run.value) return ''
  // The tag the server will push (it appends "-dev" outside the main flow).
  const tag = releaseTag(run.value) ?? 'the next tag'
  const branches =
    run.value.sourceBranch && run.value.targetBranch
      ? `${run.value.sourceBranch} into ${run.value.targetBranch}`
      : 'the merge request'
  return `Ready to merge ${branches} and tag ${tag}. Choose Wait if you'll merge it yourself on GitLab.`
})
</script>

<template>
  <div class="flex flex-col gap-4">
    <RouterLink
      to="/runs"
      class="inline-flex w-fit items-center gap-1.5 text-sm text-text-muted transition-colors hover:text-text focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"
    >
      <Icon name="chevron-down" size="sm" class="rotate-90" />
      Runs
    </RouterLink>

    <div v-if="state.status === 'pending'" class="flex flex-col gap-2" data-testid="run-detail-loading">
      <Skeleton class="h-6 w-64" />
      <Skeleton class="h-4 w-40" />
      <Skeleton class="h-24 w-full" />
    </div>

    <Alert v-else-if="state.status === 'error' && isNotFound(error)" status="info" data-testid="run-not-found">
      <p>This run no longer exists. It may have been discarded or removed.</p>
      <RouterLink
        to="/runs"
        class="mt-2 inline-flex items-center text-sm font-medium text-accent-text underline-offset-2 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"
      >
        Back to runs
      </RouterLink>
    </Alert>

    <Alert v-else-if="state.status === 'error'" status="danger">
      <p>{{ resolveErrorMessage(error, 'Failed to load run') }}</p>
      <Button variant="outline" size="sm" class="mt-2" @click="refetch()">Retry</Button>
    </Alert>

    <template v-else-if="run">
      <section class="flex flex-col gap-2">
        <div class="flex items-center gap-2">
          <RouterLink
            v-if="repoFlowLink"
            :to="repoFlowLink"
            class="text-sm text-text-muted transition-colors hover:text-text hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"
            data-testid="run-detail-repo-link"
          >
            {{ run.repoName ?? 'Unknown repo' }}
          </RouterLink>
          <template v-if="mergeRequest">
            <span class="text-sm text-text-muted" aria-hidden="true">·</span>
            <a
              v-if="mergeRequest.url"
              :href="mergeRequest.url"
              target="_blank"
              rel="noopener"
              class="inline-flex items-center gap-1 text-sm text-text-muted transition-colors hover:text-text hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus-ring"
              data-testid="run-detail-mr-link"
            >
              MR !{{ mergeRequest.iid }}
              <Icon name="external-link" size="xs" />
              <span class="sr-only">(opens GitLab in a new tab)</span>
            </a>
            <Text v-else muted size="sm">MR !{{ mergeRequest.iid }}</Text>
          </template>
          <span
            v-if="isPolling"
            class="flex items-center gap-1 text-xs text-text-muted"
            data-testid="run-detail-live-indicator"
          >
            <span class="size-1.5 animate-pulse rounded-full bg-success-solid motion-reduce:animate-none" />
            Live
          </span>
        </div>
        <Text as="h1" size="xl" class="font-semibold tracking-tight">{{ runTitle(run) }}</Text>
        <div class="flex flex-wrap items-center gap-2">
          <RunStatusChip :status="run.status" />
          <Badge status="neutral">{{ routineKindLabel[run.kind] }}</Badge>
          <Badge v-if="run.kind === 'release' && flowLabel(run.flow)" status="neutral">
            {{ flowLabel(run.flow) }}
            <template v-if="run.sourceBranch && run.targetBranch">
              — {{ run.sourceBranch }}→{{ run.targetBranch }}
            </template>
          </Badge>
          <Text muted size="xs">
            Created {{ formatDateTime(run.createdAt) }} · Updated {{ formatDateTime(run.updatedAt) }}
          </Text>
        </div>
      </section>

      <Alert v-if="run.lastError" status="danger" title="Last error" data-testid="run-last-error">
        {{ run.lastError }}
      </Alert>

      <section
        v-if="stateSummaryEntries(run).length > 0"
        class="flex flex-col gap-2 rounded-lg border border-line-subtle bg-bg-panel p-3"
      >
        <Text size="sm" class="font-medium">State</Text>
        <dl class="grid grid-cols-2 gap-x-4 gap-y-2 sm:grid-cols-3">
          <div v-for="entry in stateSummaryEntries(run)" :key="entry.key" class="flex flex-col">
            <dt class="text-xs text-text-muted">{{ entry.label }}</dt>
            <dd class="text-sm text-text">{{ entry.value }}</dd>
          </div>
        </dl>
      </section>

      <section class="flex flex-col gap-2 rounded-lg border border-line-subtle bg-bg-panel p-3">
        <Text size="sm" class="font-medium">Steps</Text>
        <StepTimeline :steps="run.steps" :attention-step="attentionStep">
          <template #attention>
            <div
              v-if="run.status === 'awaiting_confirmation'"
              class="flex flex-col gap-2 rounded-md border border-line-subtle bg-bg-app p-3"
            >
              <Text size="sm">{{ mergeSummary }}</Text>
              <div class="flex flex-wrap items-center gap-2">
                <ConfirmDialog
                  title="Merge and tag now?"
                  :description="mergeConfirmDescription"
                  confirm-label="Merge now"
                  :pending="isConfirming"
                  @confirm="handleConfirm('merge')"
                >
                  <template #trigger>
                    <Button variant="accent" size="sm" :loading="isConfirming">Merge</Button>
                  </template>
                </ConfirmDialog>
                <Button variant="outline" size="sm" :loading="isConfirming" @click="handleConfirm('wait')">
                  Wait
                </Button>
              </div>
            </div>
            <div v-else-if="run.status === 'blocked'" class="flex flex-wrap items-center gap-2">
              <Button variant="accent" size="sm" :loading="isResuming" @click="handleResume">Resume</Button>
              <Button variant="outline" size="sm" :loading="isSkipping" @click="handleSkip">Skip</Button>
            </div>
          </template>
        </StepTimeline>
      </section>

      <section
        v-if="(!attentionStep && (run.status === 'blocked' || run.status === 'awaiting_confirmation')) || isRunCancelable(run.status)"
        class="flex flex-wrap items-center gap-2"
      >
        <Button v-if="!attentionStep && run.status === 'blocked'" variant="accent" size="sm" :loading="isResuming" @click="handleResume">
          Resume
        </Button>
        <Button v-if="!attentionStep && run.status === 'blocked'" variant="outline" size="sm" :loading="isSkipping" @click="handleSkip">
          Skip
        </Button>
        <template v-if="!attentionStep && run.status === 'awaiting_confirmation'">
          <ConfirmDialog
            title="Merge and tag now?"
            :description="mergeConfirmDescription"
            confirm-label="Merge now"
            :pending="isConfirming"
            @confirm="handleConfirm('merge')"
          >
            <template #trigger>
              <Button variant="accent" size="sm" :loading="isConfirming">Merge</Button>
            </template>
          </ConfirmDialog>
          <Button variant="outline" size="sm" :loading="isConfirming" @click="handleConfirm('wait')">Wait</Button>
        </template>
        <ConfirmDialog
          v-if="isRunCancelable(run.status)"
          title="Cancel this run?"
          description="Stops the routine run in progress. This cannot be undone."
          confirm-label="Cancel run"
          :pending="isCancelling"
          @confirm="handleCancel"
        >
          <template #trigger>
            <Button variant="ghost" size="sm" class="text-danger-text hover:bg-danger-bg">Cancel</Button>
          </template>
        </ConfirmDialog>
      </section>
    </template>
  </div>
</template>

<route lang="json">
{ "meta": { "title": "Run" } }
</route>
