/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/design': RouteRecordInfo<
      '/design',
      '/design',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flow/': RouteRecordInfo<
      '/flow/',
      '/flow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/flow/[repoId]': RouteRecordInfo<
      '/flow/[repoId]',
      '/flow/:repoId',
      { repoId: ParamValue<true> },
      { repoId: ParamValue<false> },
      | never
    >,
    '/reviews/': RouteRecordInfo<
      '/reviews/',
      '/reviews',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reviews/[id]': RouteRecordInfo<
      '/reviews/[id]',
      '/reviews/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/runs/': RouteRecordInfo<
      '/runs/',
      '/runs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/runs/[id]': RouteRecordInfo<
      '/runs/[id]',
      '/runs/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/accounts': RouteRecordInfo<
      '/settings/accounts',
      '/settings/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications-security': RouteRecordInfo<
      '/settings/notifications-security',
      '/settings/notifications-security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/profiles': RouteRecordInfo<
      '/settings/profiles',
      '/settings/profiles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/providers': RouteRecordInfo<
      '/settings/providers',
      '/settings/providers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/repos': RouteRecordInfo<
      '/settings/repos',
      '/settings/repos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/telegram': RouteRecordInfo<
      '/settings/telegram',
      '/settings/telegram',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/design.vue': {
      routes:
        | '/design'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/flow/index.vue': {
      routes:
        | '/flow/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/flow/[repoId].vue': {
      routes:
        | '/flow/[repoId]'
      views:
        | never
      pathParamNames:
        | 'repoId'
    }
    'src/pages/reviews/index.vue': {
      routes:
        | '/reviews/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reviews/[id].vue': {
      routes:
        | '/reviews/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/runs/index.vue': {
      routes:
        | '/runs/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/runs/[id].vue': {
      routes:
        | '/runs/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/accounts.vue': {
      routes:
        | '/settings/accounts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/notifications-security.vue': {
      routes:
        | '/settings/notifications-security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/profiles.vue': {
      routes:
        | '/settings/profiles'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/providers.vue': {
      routes:
        | '/settings/providers'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/repos.vue': {
      routes:
        | '/settings/repos'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/telegram.vue': {
      routes:
        | '/settings/telegram'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
